"""Build the Content Desk into docs/desk/ for GitHub Pages.

Source of truth is social/dashboard/ — index.html plus data.js, which read media
straight out of content/ when you open them off disk. docs/ can't reach outside
itself once published, and the raw carousel PNGs are ~26 MB, so this script:

  * inlines data.js into the page (one file, no fetch)
  * rewrites the BUILD:CONFIG block to point at the bundled media/
  * downscales the carousel PNGs to JPEG and copies the reel MP4s across

Run it after editing anything in social/dashboard/ or content/:

    python social/dashboard/build_desk.py

Output: docs/desk/index.html + docs/desk/media/. Published at
<pages-url>/desk/. Note that GitHub Pages is public even from a private repo —
anything in here is readable by anyone with the link. Review notes typed into
the desk are held in browser localStorage and are never part of this build.
"""

import os
import re
import shutil
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
CONTENT = os.path.join(ROOT, "content")
DIST = os.path.join(ROOT, "docs", "desk")
MEDIA = os.path.join(DIST, "media")

# Wide enough that a slide's rule text is readable full-screen on a phone,
# small enough that seventeen of them aren't a mobile-data event.
SLIDE_WIDTH = 900
SLIDE_QUALITY = 80
PFP_SIZE = 96

CONFIG = """/* BUILD:CONFIG — generated by social/dashboard/build_desk.py. Do not edit here. */
const MEDIA_BASE = 'media/';
const IMG_EXT    = '.jpg';
const PFP        = 'media/pfp.png';
/* /BUILD:CONFIG */"""


def fail(msg):
    print("build_desk: " + msg, file=sys.stderr)
    sys.exit(1)


def build_page():
    page = open(os.path.join(HERE, "index.html"), encoding="utf-8").read()
    data = open(os.path.join(HERE, "data.js"), encoding="utf-8").read()

    page, n = re.subn(
        r"/\* BUILD:CONFIG.*?/\* /BUILD:CONFIG \*/",
        lambda m: CONFIG,
        page,
        flags=re.S,
    )
    if n != 1:
        fail("expected exactly one BUILD:CONFIG block in index.html, found %d" % n)

    tag = '<script src="data.js"></script>'
    if tag not in page:
        fail("could not find %s in index.html" % tag)
    page = page.replace(tag, "<script>\n" + data + "\n</script>")

    if "data.js" in page.split("<script>")[0]:
        fail("a reference to data.js survived inlining")

    os.makedirs(DIST, exist_ok=True)
    dest = os.path.join(DIST, "index.html")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(page)
    return dest


def folders_in_data():
    data = open(os.path.join(HERE, "data.js"), encoding="utf-8").read()
    seen = []
    for m in re.finditer(r"folder:\s*'([^']+)'", data):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    return seen


def _slice_array(text, open_at):
    """Return the source of the [...] starting at `open_at`, brackets included."""
    depth = 0
    for i in range(open_at, len(text)):
        if text[i] == "[":
            depth += 1
        elif text[i] == "]":
            depth -= 1
            if depth == 0:
                return text[open_at:i + 1]
    fail("unterminated slides array in data.js")


def check_slides():
    """Every `slides` entry must be a ['<stem>', '<label>'] pair, extensionless.

    The desk builds both the preview and the save list from that shape:
    index.html does `p.slides.map(([f, label]) => ...)` and appends IMG_EXT
    itself, because the preview wants the bundled .jpg and the save wants the
    original .png. Destructuring is silent on the wrong shape -- given a bare
    string '01_cover.png' it takes the first *character*, so every slide
    resolves to '0.png'. carousel-post-5 shipped that way on 2026-09-02: the
    thumbnails 404'd and "Save all 8 slides" failed on every slide, with
    nothing anywhere saying why. Min-Yi reported it as "carousel post media
    seems unsavable" on 2026-09-03.

    Nothing else in the pipeline reads `slides`, so this is the only place the
    shape can be enforced. Checked here rather than in index.html because a
    build that cannot produce a working page should not produce a page at all.
    """
    data = open(os.path.join(HERE, "data.js"), encoding="utf-8").read()
    # The stem is always single-quoted; the label may be single-quoted,
    # double-quoted or a template literal, because several carry an apostrophe
    # ("You're allowed to leave the field") or nested double quotes.
    entry = re.compile(
        r"""\A\[\s*'([^']+)'\s*,\s*"""
        r"""(?:'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"|`(?:[^`\\]|\\.)*`)\s*\]\Z""",
        re.S)
    folder = None
    problems = []

    for m in re.finditer(r"folder:\s*'([^']+)'|slides:\s*(\[)", data):
        if m.group(1):
            folder = m.group(1)
            continue
        block = _slice_array(data, m.start(2))
        if block.strip() == "[]":
            continue
        # Split on top-level commas only, so labels containing commas survive.
        depth, buf, items = 0, "", []
        for ch in block[1:-1]:
            if ch in "[":
                depth += 1
            elif ch in "]":
                depth -= 1
            if ch == "," and depth == 0:
                items.append(buf); buf = ""
            else:
                buf += ch
        if buf.strip():
            items.append(buf)

        for raw in items:
            item = raw.strip()
            hit = entry.match(item)
            if not hit:
                problems.append(
                    "%s: slide entry is not a ['<stem>', '<label>'] pair: %s"
                    % (folder, item[:60]))
                continue
            stem = hit.group(1)
            if os.path.splitext(stem)[1]:
                problems.append(
                    "%s: slide stem carries a file extension (%r) -- the desk "
                    "appends IMG_EXT itself" % (folder, stem))
                continue
            png = os.path.join(CONTENT, folder, stem + ".png")
            if not os.path.exists(png):
                problems.append("%s: slides references %s.png, which is not on disk"
                                % (folder, stem))

    if problems:
        fail("malformed slides in data.js —\n  " + "\n  ".join(problems))


def build_media():
    if os.path.isdir(MEDIA):
        shutil.rmtree(MEDIA)
    os.makedirs(MEDIA, exist_ok=True)

    total = 0
    for folder in folders_in_data():
        src_dir = os.path.join(CONTENT, folder)
        if not os.path.isdir(src_dir):
            fail("content/%s referenced in data.js but missing on disk" % folder)
        out_dir = os.path.join(MEDIA, folder)
        os.makedirs(out_dir, exist_ok=True)

        for name in sorted(os.listdir(src_dir)):
            src = os.path.join(src_dir, name)
            stem, ext = os.path.splitext(name)
            ext = ext.lower()

            # Superseded cuts (<name>.v1.mp4) stay out of the bundle -- the desk
            # previews those from the repo instead, so history doesn't cost
            # every phone another megabyte per round.
            if re.search(r"\.v\d+$", stem):
                continue

            if ext == ".png":
                out = os.path.join(out_dir, stem + ".jpg")
                with Image.open(src) as im:
                    im = im.convert("RGB")
                    if im.width > SLIDE_WIDTH:
                        h = round(im.height * SLIDE_WIDTH / im.width)
                        im = im.resize((SLIDE_WIDTH, h), Image.LANCZOS)
                    im.save(out, "JPEG", quality=SLIDE_QUALITY, optimize=True,
                            progressive=True)
            elif ext == ".mp4":
                out = os.path.join(out_dir, name)
                shutil.copy2(src, out)
            else:
                continue

            total += os.path.getsize(out)

    pfp_src = os.path.join(
        ROOT, "social", "logos", "profile", "luf",
        "learn-ultimate-frisbee-pfp-bold-final.png")
    if os.path.exists(pfp_src):
        with Image.open(pfp_src) as im:
            im = im.convert("RGB").resize((PFP_SIZE, PFP_SIZE), Image.LANCZOS)
            im.save(os.path.join(MEDIA, "pfp.png"), "PNG", optimize=True)
        total += os.path.getsize(os.path.join(MEDIA, "pfp.png"))
    else:
        print("build_desk: warning — profile image missing, header falls back to initials")

    return total


def main():
    check_slides()
    page = build_page()
    media_bytes = build_media()
    print("built docs/desk/")
    print("  index.html  %6.0f KB" % (os.path.getsize(page) / 1024))
    print("  media/      %6.1f MB" % (media_bytes / 1024 / 1024))


if __name__ == "__main__":
    main()
