"""Build the Content Desk into docs/desk/ for GitHub Pages.

Source of truth is social/dashboard/ — index.html plus data.js, which read media
straight out of content/ when you open them off disk. docs/ can't reach outside
itself once published, and the raw carousel PNGs are ~26 MB, so this script:

  * inlines data.js into the page (one file, no fetch)
  * rewrites the BUILD:CONFIG block to point at the bundled media/
  * downscales the carousel PNGs to JPEG and copies the reel MP4s across

Run it after editing anything in social/dashboard/ or content/:

    python social/dashboard/build_desk.py

Output: docs/desk/index.html + docs/desk/media/. Published at
<pages-url>/desk/. Note that GitHub Pages is public even from a private repo —
anything in here is readable by anyone with the link. Review notes typed into
the desk are held in browser localStorage and are never part of this build.
"""

import os
import re
import shutil
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
CONTENT = os.path.join(ROOT, "content")
DIST = os.path.join(ROOT, "docs", "desk")
MEDIA = os.path.join(DIST, "media")

# Wide enough that a slide's rule text is readable full-screen on a phone,
# small enough that seventeen of them aren't a mobile-data event.
SLIDE_WIDTH = 900
SLIDE_QUALITY = 80
PFP_SIZE = 96

CONFIG = """/* BUILD:CONFIG — generated by social/dashboard/build_desk.py. Do not edit here. */
const MEDIA_BASE = 'media/';
const IMG_EXT    = '.jpg';
const PFP        = 'media/pfp.png';
/* /BUILD:CONFIG */"""


def fail(msg):
    print("build_desk: " + msg, file=sys.stderr)
    sys.exit(1)


def build_page():
    page = open(os.path.join(HERE, "index.html"), encoding="utf-8").read()
    data = open(os.path.join(HERE, "data.js"), encoding="utf-8").read()

    page, n = re.subn(
        r"/\* BUILD:CONFIG.*?/\* /BUILD:CONFIG \*/",
        lambda m: CONFIG,
        page,
        flags=re.S,
    )
    if n != 1:
        fail("expected exactly one BUILD:CONFIG block in index.html, found %d" % n)

    tag = '<script src="data.js"></script>'
    if tag not in page:
        fail("could not find %s in index.html" % tag)
    page = page.replace(tag, "<script>\n" + data + "\n</script>")

    if "data.js" in page.split("<script>")[0]:
        fail("a reference to data.js survived inlining")

    os.makedirs(DIST, exist_ok=True)
    dest = os.path.join(DIST, "index.html")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(page)
    return dest


def folders_in_data():
    data = open(os.path.join(HERE, "data.js"), encoding="utf-8").read()
    seen = []
    for m in re.finditer(r"folder:\s*'([^']+)'", data):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    return seen


def build_media():
    if os.path.isdir(MEDIA):
        shutil.rmtree(MEDIA)
    os.makedirs(MEDIA, exist_ok=True)

    total = 0
    for folder in folders_in_data():
        src_dir = os.path.join(CONTENT, folder)
        if not os.path.isdir(src_dir):
            fail("content/%s referenced in data.js but missing on disk" % folder)
        out_dir = os.path.join(MEDIA, folder)
        os.makedirs(out_dir, exist_ok=True)

        for name in sorted(os.listdir(src_dir)):
            src = os.path.join(src_dir, name)
            stem, ext = os.path.splitext(name)
            ext = ext.lower()

            # Superseded cuts (<name>.v1.mp4) stay out of the bundle -- the desk
            # previews those from the repo instead, so history doesn't cost
            # every phone another megabyte per round.
            if re.search(r"\.v\d+$", stem):
                continue

            if ext == ".png":
                out = os.path.join(out_dir, stem + ".jpg")
                with Image.open(src) as im:
                    im = im.convert("RGB")
                    if im.width > SLIDE_WIDTH:
                        h = round(im.height * SLIDE_WIDTH / im.width)
                        im = im.resize((SLIDE_WIDTH, h), Image.LANCZOS)
                    im.save(out, "JPEG", quality=SLIDE_QUALITY, optimize=True,
                            progressive=True)
            elif ext == ".mp4":
                out = os.path.join(out_dir, name)
                shutil.copy2(src, out)
            else:
                continue

            total += os.path.getsize(out)

    pfp_src = os.path.join(
        ROOT, "social", "logos", "profile", "luf",
        "learn-ultimate-frisbee-pfp-bold-final.png")
    if os.path.exists(pfp_src):
        with Image.open(pfp_src) as im:
            im = im.convert("RGB").resize((PFP_SIZE, PFP_SIZE), Image.LANCZOS)
            im.save(os.path.join(MEDIA, "pfp.png"), "PNG", optimize=True)
        total += os.path.getsize(os.path.join(MEDIA, "pfp.png"))
    else:
        print("build_desk: warning — profile image missing, header falls back to initials")

    return total


def main():
    page = build_page()
    media_bytes = build_media()
    print("built docs/desk/")
    print("  index.html  %6.0f KB" % (os.path.getsize(page) / 1024))
    print("  media/      %6.1f MB" % (media_bytes / 1024 / 1024))


if __name__ == "__main__":
    main()
